### ISSUE TITLE
Load preset does nothing

### ISSUE THREAD

**Issue by ormanya** [ratanakvlun/deluge-ltconfig#14]
When I choose a new preset and click Load Preset nothing happens, clicking Apply in settings window, then coming back to ltconfig settings and still no changes. Both the setting and actual columns are unchanged. 

Using:
Deluge GTK client: OS X 1.3.15
Deluged: Linux 1.3.15
lib torrent: 1.0.11.0
ltconfig: 0.3.1

**Comment by ratanakvlun** [comment]
Are you able to change individual settings?

**Comment by ormanya** [comment]
Yes, I can change individual settings

**Comment by ratanakvlun** [comment]
When you click Load Preset, it doesn't show the changes in the setting column?

**Comment by ormanya** [comment]
[ltconfig.mov.zip](https://github.com/ratanakvlun/deluge-ltconfig/files/1105951/ltconfig.mov.zip)

Correct. The setting column does not change and none of the settings change from grey to black font. If I make the change, exit Preferences, then go back in, the preset dropdown still shows my new selection (but no changes in actual settings). However, if I disconnect the thin client then reconnect it, the dropdown is reset to Pre-ltConfig Settings. It seems that the change is only being made in the thin client and not registering with the server. I attached a movie showing the behaviour.

**Comment by ratanakvlun** [comment]
I am unable to access the movie file. Can you check the url?

**Comment by ormanya** [comment]
Hmmm, strange. I just uploaded it via the github file attachment tool. Try this instead: http://www.sekrit.me/ltconfig.mov

**Comment by ratanakvlun** [comment]
Managed to get access to macOS 10.12 and tested this with the official Deluge 1.3.15/libtorrent 1.0.9 dmg. It seems to be working for me.

Make sure both your server and client are using the same ltConfig version. You will have to restart both the server and client.

If it still does not work, try running with logging enabled and look for error messages when you click Load Preset.

**Comment by ormanya** [comment]
Both are using ltconfig 0.3.1. I also tried restarting the server and client.
I checked deluged.log on the server and there were no errors associated with ltconfig. I can't see any way to enable logging on the client end in deluge.app.

Two things that may be helpful:
1. I am running lib torrent 1.0.11; you tested with 1.0.9
2. While the client is running on macOS, the server is running on  Debian 8

**Comment by ormanya** [comment]
So removed and reinstalled ltconfig. Still no effect of load preset. I then checked the Apply Settings on startup box, and I could see that this took effect on the server (see log below). Therefore, the client is communicating with the server and is able to save settings on the server. It seems the problem is really limited to loading the preset in the client.

Note that I am using the the deluge.app client (GTK). Is that what you used for testing?

Log of preference changes I described above:
https://ghostbin.com/paste/zaqoj

**Comment by ormanya** [comment]
One more thing as a test. I disabled ltconfig in the macOS client, connected via the web client, installed ltconfig again. In the web client I can see the settings page and make manual changes, but the dropdown menu of presets is greyed out and inaccessible: https://puu.sh/wxtSU/2d1344e221.png

**Comment by ratanakvlun** [comment]
Yes, I am testing with the gtk client. Where did you get the libtorrent 1.0.11 binary?

The only code in the webui that disables the presets is if the version is less than 0.16, so that is weird.

**Comment by ormanya** [comment]
It is on his github page: https://github.com/arvidn/libtorrent/releases

However, I am running this on a seedbox, so I did not install the server side myself.

**Comment by ratanakvlun** [comment]
Also, you can enable logging for the client by running the gtk client binary (should be in the deluge.app directory somewhere) from terminal and using the `-l` and `-L` flags (use --help for better explanation of these). Log level should be `debug`.

**Comment by ratanakvlun** [comment]
When you click `Load Preset`, the daemon log (log level debug) should show:
```
[ltConfig] Get preset 2
```
On client log (log level debug), you should see something like:
```
[ltConfig] Loading preset...
[ltConfig] Option=2
```
Where 2 is a number corresponding to the preset index.

**Comment by ormanya** [comment]
I have enabled logging on both. When I make changes to individual ltconfig settings or to load settings on startup, I can see the changes logged on the server (and the ltconfig.conf file is updated). However, when I try to load a preset I see nothing in the logs.

**Comment by ormanya** [comment]
In the client log, I see the ltconfig egg file loaded, but then there is no subsequent mention of ltconfig.

**Comment by ratanakvlun** [comment]
And no errors?

**Comment by ormanya** [comment]
No errors. Absolutely nothing gets written to the log when I press the Load Preset button

**Comment by ratanakvlun** [comment]
And log level is set to `debug`? What version of macOS are you on? This sounds like the button is not linked to the button logic correctly.

**Comment by ormanya** [comment]
I started logging on the client system with "/Users/me/Applications/Deluge.app/Contents/MacOS/deluged -L debug -l ~/.config/deluge/deluged.log"

I am running MacOS 10.12.5.

**Comment by ratanakvlun** [comment]
If you are on the client system, you should run `deluge` or `Deluge`. `deluged` is for the daemon.

**Comment by ratanakvlun** [comment]
I set up a Deluge 1.3.15, libtorrent 1.0.11 daemon on Debian 8 and used the official Deluge 1.3.15 dmg on macOS 10.12 as the thin client. I can't seem to reproduce the problem.

**Comment by ormanya** [comment]
Alright. I guess we are stuck! Only reasonable explanation at this point is that it someone on my seedbox companies end, although I am not sure how that would work since I am not seeing a log entry AND I can make manual changes to individual settings. As a workaround, is there anywhere I can find the list of configurations associated with each preset so that I can manually apply them?

**Comment by ratanakvlun** [comment]
You can find the presets [here](https://github.com/ratanakvlun/deluge-ltconfig/blob/6c524fcc/ltconfig/common/presets.py).

Some settings may not exist in the current libtorrent version and can be ignored.
