### ISSUE TITLE
force-proxy option missing

### ISSUE THREAD

**Issue by meeotch** [ratanakvlun/deluge-ltconfig#16]
I seem to be missing the force-proxy option.  The alphabetical list goes right from "file_pool_size" to "free_torrrent_hashes".

Is this possibly a version thing? I'm on libtorrent 0.16.13.0.

**Comment by ratanakvlun** [comment]
It is a version thing. Not sure when the option was introduced, but it is present on my test system with libtorrent 1.1.1.0.
