### ISSUE TITLE
How to install 2.0.0 manually?

### ISSUE THREAD

**Issue by raphaelyancey** [ratanakvlun/deluge-ltconfig#20]
The [manual plugin installation](https://dev.deluge-torrent.org/wiki/Plugins#Install) doesn't seem to work. I've renamed the egg to `ltConfig-2.0.0-py3.7.egg` and placed it into the `plugins` config directory, but it doesn't get installed when I restart Deluge.

I'm running the LSIO docker image of Deluge (2.x).

**Comment by k-304** [comment]
Its working for me in Deluge 2. Try to:
Place the .egg file in the plugins dir and check the permissions.
Stop DelugeD and web service, start it. 
Go to Config --> Plugins and enable it. 
Then stop deluged and the web service again, then start it.
You should now be able to see ltconfig in your configurations menu.

**Comment by raphaelyancey** [comment]
The plugin won't show in `Config > Plugins` unfortunately, even after a restart. Its permissions are:

```bash
-rwxr-xr-x ltConfig-2.0.0-py3.7.egg
```

Maybe the naming isn't correct?

**Comment by k-304** [comment]
I used the following download link: https://github.com/ratanakvlun/deluge-ltconfig/releases/download/v2.0.0/ltConfig-2.0.0.egg and did not change the name at all.
ls -ali plugins/ shows:
`-rwxr--r-- 1 deluge deluge 46072 Jan  4 14:16 ltConfig-2.0.0.egg`

**Comment by raphaelyancey** [comment]
I removed `-py3.7` and it worked, thanks. The solution was just to set the `o+x` permission after all :)
