### ISSUE TITLE
ltConfig-2.0.0 doesn't work with Deluge 2.0.4

### ISSUE THREAD

**Issue by gitsnow** [ratanakvlun/deluge-ltconfig#21]
I've been successfully using the ltConfig plugin with Deluge version 2.0.3, but recently the docker maintainer I use upgraded to version 2.0.4 which caused all of the torrents to stop working.  I've tried setting up a new docker container with 2.0.4 and recompiling the plugin, but this didn't fix the issue.  I was forced to rollback to 2.0.3.

Is it possible for you to update the plugin to work with the Deluge 2.0.4?

**Comment by iusearch** [comment]
It seems like, it only opens ports for udp with high performance seeding preset. Libtorrent defaults are working fine.

**Comment by boredness** [comment]
deluged 2.0.4.dev23
libtorrent: 1.2.6.0
Python: 3.8.2
OS: Arch

when adding the egg nothing happens.

**Comment by pazport** [comment]
this doesn't work on deluge 2.0.3 , could this get updated and fix please.

**Comment by mhertz** [comment]
Works here, on both 2.0.3 and 2.0.4.dev38, on both archlinux and windows.

**Comment by gitsnow** [comment]
> Works here, on both 2.0.3 and 2.0.4.dev38, on both archlinux and windows.

Thanks for commenting mhertz.  I just tested on 2.0.4.dev38 which is also the latest build of binhex-delugevpn and it works now.  It wasn't working on earlier 2.0.4 builds.
