### ISSUE TITLE
No module named config.file.

### ISSUE THREAD

**Issue by elektito** [ratanakvlun/deluge-ltconfig#4]
I cloned the repository from github, built the egg with `python setup.py bdist_egg` and added the plugin to Deluge, but then I noticed that I cannot enable it. As soon as I hit the apply button in Deluge preferences, the ltconfig check box is cleared. So I checked Deluge's log file and found this error message:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/deluge/pluginmanagerbase.py", line 144, in enable_plugin
        instance = cls(plugin_name.replace("-", "_"))
      File "build/bdist.linux-x86_64/egg/ltconfig/__init__.py", line 46, in __init__
        from core import Core as _plugin_cls
      File "build/bdist.linux-x86_64/egg/ltconfig/core.py", line 50, in <module>
    ImportError: No module named config.file

Checking the source I see that this line in core.py causes the exception:

    from common.config.file import init_config

Obviously there is no such module. I'm not familiar with Deluge plugin writing. Is that a file Deluge is supposed to provide? Should I do something different? Or is this simply a bug?

I'm using Deluge 1.3.6 and libtorrent 0.16.13.0 on Ubuntu 14.04.

**Comment by ratanakvlun** [comment]
Wow, you are right. Apparently, I didn't check in that directory to github. I've added it to the repo (1fce5216526e26734ec8e0383575567661f4f09f).
