### ISSUE TITLE
broken for new releases (1.1.X)

### ISSUE THREAD

**Issue by smdrz** [ratanakvlun/deluge-ltconfig#5]
itconfig won't start and deluge functions wierd (bandwidth limits are not passed or set properly) for libtorrent 1.1.x

**Comment by ratanakvlun** [comment]
It is working fine for me on Debian with Deluge 1.3.12 and libtorrent 1.1.0. You will have to be more specific about your setup before I can troubleshoot this.

**Comment by niayh** [comment]
Same issue as the original poster for me as well.

Currently running debian stretch with Deluge 1.3.12 from the stretch repo and a self-compiled version of libtorrent 1.1.0.

ltConfig appears to be loaded in the list of plugins, but does not show up in the settings and it is not configurable. Settings cannot even be written manually to the ltconfig.conf. Deluge seems to allow the settings file to coexist with itself; however, upon shutting down Deluge, the ltconfig.conf is rewritten with default (null) values.

**Comment by ratanakvlun** [comment]
Hmm. I've only tested Debian Jessie with manual Deluge 1.3.12 and libtorrent 1.1.0 builds. I will try to set up a Stretch environment, but if possible, could you provide some Deluge logs?

**Comment by ratanakvlun** [comment]
I set up a Debian Stretch environment and manually built Deluge 1.3.12 and libtorrent 1.1.0. I am not seeing this issue in this environment. I built Deluge from the 1.3-stable branch of the Deluge [git repo](http://git.deluge-torrent.org/deluge) and I built libtorrent 1.1.0 from branch [RC_1_1](https://github.com/arvidn/libtorrent/tree/RC_1_1) of the libtorrent github repo.

If you haven't already, you should try to build from these branches.

**Comment by niayh** [comment]
Ahah! This worked perfectly -- I was compiling both Deluge 1.3.12 and libtorrent 1.1.0 from the pre-rolled tarballs. Switching to the up-to-date for each branch works perfectly!

**Comment by ratanakvlun** [comment]
Closing because this seems to be a libtorrent issue that can be resolved by building the latest libtorrent RC_1_1 branch.
