### ISSUE TITLE
Certain values not setting or displaying properly (1.1.0)

### ISSUE THREAD

**Issue by niayh** [ratanakvlun/deluge-ltconfig#6]
Now that I've had a chance to properly explore libtorrent 1.1.0 with ltConfig, I've come across a few things that are starting to niggle me in some of the settings.

First up, I'm assuming that ltConfig dynamically loads configurable values from libtorrent at time of boot and loads the defaults -- this explains how the presets seem to change with each version of libtorrent while the plugin stays static. If a setting disappears, does this mean it was removed from session_settings/settings_pack?

For instance, suggest_mode no longer seems to appear in the settings; however it is most certainly still an option in the settings pack (http://www.libtorrent.org/reference-Settings.html). Other new options remain off the list as well (aio_threads, network_threads to name a few)

Additionally, certain values just don't set properly, it leads me to wonder exactly how they are being set and with what values:
https://gyazo.com/a4d7ad9cf1050eac218343a2e92d3bbc
https://gyazo.com/355f2a6c9a0608903b09c5642243f8bf
https://gyazo.com/71372eb78a94e0b94599f573002624b1

For instance disk_cache_algorithm has always been set to two for me and now it seems that 2 (avoid_readback) is not an acceptable value.

Another thing seems to be the cache_chunk_size which the high performance preset now sets to 0 (as per documentation, dynamically adjusts cache chunk size based on cache size). However, when set as 0, the setting seems to set at 1.

If I can provide any other info, please let me know. At this point, I don't know if it's deluge continuing to use deprecated functions (deluge won't start if they are disabled), libtorrent or ltConfig.

**Comment by ratanakvlun** [comment]
Generally, yes, the plugin just gets whatever settings are exposed by libtorrent. There are some settings that are not included in session_settings (for instance, dht_settings is its own thing), so that may be a reason it is omitted. I'll have to take a look and see if I can include more of the available settings.

**Comment by ratanakvlun** [comment]
Since ltConfig targets Deluge 1.3.x which doesn't support libtorrent 1.1.x, I won't be supporting that version either.
