### ISSUE TITLE
libtorrent 1.1.0.0 and Deluge 1.3.3

### ISSUE THREAD

**Issue by klunky** [ratanakvlun/deluge-ltconfig#7]
Hello,

You think you will be able to release a new ltConfig version to be able to edit settings on Deluge 1.3.3 ?

Thanks for great work !

**Comment by BabaBooey84** [comment]
I'm wondering the same thing, will we see a version that works with 1.3.13?
The plugin is really nice and I miss it. I had to upgrade to the latest Deluge version due to all the bug fixes, and Itconfig plugin doesn't seem to work. I couldn't make it run at least :cry:

**Comment by ratanakvlun** [comment]
ltConfig won't be supporting libtorrent 1.1.x.

The plugin should still work with Deluge 1.3.13 and libtorrent 1.0.9. If you are having issues with this set up, then please open another issue.
