### ISSUE TITLE
what not support new 1.0.10

### ISSUE THREAD

**Issue by zuroba** [ratanakvlun/deluge-ltconfig#8]
what now you not do new build to support 1.0.10

https://github.com/arvidn/libtorrent/releases

**Comment by zuroba** [comment]
@ratanakvlun u r still here

**Comment by ratanakvlun** [comment]
yes i am still here. just very busy with some other work right now. i expect to have some free time in the near future to work on these things.

**Comment by ratanakvlun** [comment]
Should be supported with v0.3.0.
